### ISSUE TITLE
Remove unused operatorfabric.security.* config in common.yml

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1348]
in common-dev.yml : 

```
  security:
    oauth2:
      client-id: opfab-client
    jwt:
      login-claim: preferred_username
      expire-claim: exp
```
