### ISSUE TITLE
Invalid config file commons-dev.yml when uncommenting JWT parameters

### ISSUE THREAD

**Issue by quinarygio** [opfab/operatorfabric-core#1450]
File commons-dev.yml is invalid when uncommenting config section to enable getting entities or groups from JWT token.
 
This is due to "servicesUrls" parameter that should be moved above or after  "security" section .

```
security:
    oauth2:
      client-id: opfab-client
    jwt:
      login-claim: preferred_username
      expire-claim: exp
  servicesUrls:
    users: "http://localhost:2103"
### activate the folLowing if you want the entities of the user to came from the token and not mongoDB
### entitiesIdClaim is the name of the field in the token
#      entitiesIdClaim : entitiesId
#      gettingEntitiesFromToken: true
###
```
