### ISSUE TITLE
Opfab does not fully work when restarting rabbitMQ 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1669]
When restarting rabbitMQ but not the other services, the notification configuration does not work properly and connected users do not receive card update anymore unless they "refresh" the application (F5) 

This problem is due to that fact that consumer queues declared  in rabbitMQ do not persist so after a restart of rabbit , we loose queues. 

**The solution is to create durable queue in the code.** 

In addition, if OperatorFabric is used on Kubernetes environment , for the application to be resilient to pod destruction  , you must :
- persist the rabbit container repository /var/lib/rabbitmq/mnesia/ 
- declare a hostname in the rabbit container 

using docker-compose it would mean using  this example configuration : 
```
services: 
  rabbitmq: 
    image: rabbitmq:3-management
    hostname: rabbit
    volumes:
      - "./data_rabbit:/var/lib/rabbitmq/mnesia/"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"

```

See https://stackoverflow.com/questions/41330514/docker-rabbitmq-persistency for more information
