### ISSUE TITLE
Supervisor : consider user if member of specific groups 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#4901]
In the configuration , add a new parameter : **considerConnectedIfUserInGroups**

```
supervisor:
  defaultConfig:
    entitiesToSupervise:
    - id: ENTITY1_FR
      considerConnectedIfUserInGroups: ["group1","group2"]
      supervisors:
      - ENTITY2_FR
    - id: ENTITY2_FR
      supervisors:
      - ENTITY1_FR
```

If the user is not member of the groups , it is not considered as connected to the entity 

If the value is not provided then do not take into account the user group for checking entity is connected
