### ISSUE TITLE
Use servicesUrls common params for node services 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#4944]
remove form node-services.yml
```
opfab:
  usersUrl: http://users:2103
  cardsPublicationUrl: "http://cards-publication:2102"
  cardsConsultationUrl: http://cards-consultation:2104
  getTokenUrl: http://web-ui/auth/token
```

Use common.yml with existing syntax  : 
```
operatorfabric:
   servicesUrls:
     users: "http://localhost:2103"
    ....

````
