### ISSUE TITLE
Rename external recipients config params

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#4945]
```
external-recipients:
  recipients:
    - id: "processAction"
      url: "http://localhost:8090/test"
      propagateUserToken: true
    - id: "api_test_externalRecipient1"
      url: "http://localhost:8090/test"
      propagateUserToken: true
```
to be transform to 

```
operatorfabric:
  cards-publication:
      external-recipients:
        recipients:
          - id: "processAction"
            url: "http://localhost:8090/test"
            propagateUserToken: true
          - id: "api_test_externalRecipient1"
            url: "http://localhost:8090/test"
            propagateUserToken: true
```

Add in migration doc 
See impact on kafka configuration
